### PR TITLE
Implemented multi-map generation

### PR DESCRIPTION
**Pull request by Setadokalo**
This PR also includes a second way of giving those generated maps to the player (enabled by default) - what I'm calling "poster mode". The command generates all of the maps in the background, then give the player a single 'poster' map, which, when placed in an item frame, will search outwards to find enough space for the full multi-map, and if it finds it it places the entire multi-map - otherwise the poster places in the item frame normally, with it's name changed to an error message (visible on hover).
There might still be rough edges, but I think I've got it polished enough to review and potentially merge.

### CODE REVIEW

**Comment by TheEssem** [comment]
Nice PR, although I couldn't help but notice that the poster maps don't work on vertical (floor/ceiling) maps.

**Comment by Setadokalo** [comment]
yeah, I didn't implement the poster method for floor/ceiling maps mostly because it's rather hard to determine what orientation to use when on the floor - for a wall poster, it's pretty simple (just left and up from the frame's perspective), but on a floor/ceiling item frame, you have to guess what orientation to use. so no one-click sistine chapel just yet 😉

**Comment by nfej** [comment]
I've been testing this, and whenever I try to make a 1x2 image, I get "Invalid Item NBT".

**Comment by Setadokalo** [comment]
hmm, I'll have to look into that tonight or tomorrow.

**Comment by NotXeos** [comment]
/mapcreate multi dither 2 2 https://i.imgur.com/IH5Qhbo.png  wouldnt work. or any image for that matter.

**Comment by Setadokalo** [comment]
in this PR, at least at the moment, image paths have to be surrounded by quotation marks again. I might be able to switch back to greedy string, I'm not sure. As for 1x2 maps, it turns out I'm a stupid dummy (who really needs to remember to test both wide *and* tall maps). I've got a fix.

**Comment by Setadokalo** [comment]
update on that: switching to greedy strings is difficult, because greedy strings apparently take priority when parsing - which means that if there's two valid commands, `/example <greedy_string_argument>` and `/example <optional_argument> <greedy_string_argument>`, and you call it as `/example 4 http://example.com`, the game parses the command as `["example", "4 http://example.com"]`, making the optional argument part of the greedy string.

**Comment by yunus-star** [comment]
does anyone know how i can download this

**Comment by TheEssem** [comment]
It's not quite ready yet, but there are some builds in the Actions tab at the top.

**Comment by Setadokalo** [comment]
alright, back to work on this - I'm thinking of changing it to be more like the `execute` command - that would make the optional arguments much easier to implement, as they could be specified in any order with any set, but it also means there would be more typing involved for running the command (`/mapcreate multi 5 5 fit true dither <url>` would become something like `/mapcreate multi 5 5 scale fit poster true url <url>`). Thoughts on that?

**Comment by TheEssem** [comment]
> alright, back to work on this - I'm thinking of changing it to be more like the `execute` command - that would make the optional arguments much easier to implement and use, as they could be specified in any order with any set (as long as the url is the last argument), but it also means there would be more typing involved for running the command (`/mapcreate multi 5 5 fit true dither <url>` would become something like `/mapcreate multi 5 5 scale fit poster true url <url>`). Thoughts on that?

Maybe, I was thinking of turning something like that into a separate command however and instead leaving /mapcreate syntax as-is for compatibility.

In terms of the URL issue, maybe we could somehow make the command use a single greedy string argument and parse that separately? Bit of a hacky solution but it could work, not too sure if it would be possible or not to "fake" the arguments on the client however.

**Comment by Setadokalo** [comment]
(first time I've ever tried responding to a github thread via email)

Doing that could probably work, and would be the closest to how the
original plugin worked, but it would mean all syntax highlighting would
stop working and I'm pretty sure syntax highlighting would have to break
too. As for backwards compatibility... it's tricky, since the upgraded
command also has things that apply to single maps. perhaps something like
`/amapcreate`, with the a standing for advanced?

**Comment by Skavos1** [comment]
I might be stupid but I downloaded the master.zip, Do I just put that in my mods folder?

**Comment by TheEssem** [comment]
You'll need to extract the JAR from the ZIP file with a name that doesn't
include "sources" or "dev" and put that in your mods folder.

**Review by lenrik1589 — COMMENTED** [review]
why would you need to set a restriction so low?

**Comment by Neubulae** [comment]
latest causes Invalid NBT issues

**Comment by ZombieNW** [comment]
So I downloaded Setadokalo's code and got it to work for 1.18, should I make it a separate pull request? Or just post it here

**Comment by TheEssem** [comment]
> So I downloaded Setadokalo's code and got it to work for 1.18, should I make it a separate pull request? Or just post it here

You should probably send a pull request on Setadokalo's repo.

**Comment by Dinoboi66** [comment]
So how do I download this??? Sorry I'm new to github and have no idea how it works

**Comment by Lebyy** [comment]
Maybe adding a functionality like taking the entire map down in your inventory by sneaking and remove the bottom left corner would be really good.

**Comment by aspnn** [comment]
Is this going to be merged?

**Comment by Patbox** [comment]
Implemented in latest release

**Pull request closed without merging**
